"""
Pure orchestration logic for the self-healing pipeline.

This module imports only the standard library so it is unit-testable without any
Azure / ADO / LLM credentials or third-party packages. All I/O is injected:

  - `ado`          an object exposing the AdoClient interface (see healer/ado.py)
  - `request_fix`  a callable (context: dict) -> fix: dict, provider-agnostic
                   (see healer/providers.py)
  - `notify`       a callable (text: str) -> None

The real wiring is assembled in function_app.py; tests pass fakes.
"""

import json
import logging

AI_BRANCH_PREFIX = "ai-fix/"  # loop-breaker: CI ignores branches under this prefix
CODE_EXTENSIONS = (".js", ".ts", ".py", ".json", ".yml", ".yaml", ".sh", ".java",
                   ".go", ".rb", ".cs", ".tf", ".bicep")

SYSTEM_PROMPT = (
    "You are a senior engineer diagnosing an Azure DevOps CI/CD pipeline failure. "
    "You are given the failed step logs and the source of the files changed in the "
    "offending commit. Identify the smallest change that fixes the failure. "
    "Respond ONLY with a JSON object, no prose and no markdown fences, of the form: "
    '{"summary": "<one line>", "files": [{"path": "<repo path>", "content": "<full new file content>"}]}. '
    "Do not modify files unrelated to the failure. If you cannot determine a safe fix, "
    'return {"summary": "no confident fix", "files": []}.'
)


# --------------------------------------------------------------------------- pure helpers
def is_ai_branch(branch: str) -> bool:
    """Loop-breaker check: is this failure already on an AI-generated branch?"""
    if not branch:
        return False
    return branch.startswith(AI_BRANCH_PREFIX) or f"refs/heads/{AI_BRANCH_PREFIX}" in branch


def parse_failed_steps(timeline_records: list) -> list:
    """Filter an ADO build timeline down to the failed task records."""
    return [rec for rec in (timeline_records or [])
            if rec.get("result") == "failed" and rec.get("type") == "Task"]


def filter_code_files(changes: list) -> list:
    """From a commit's change list, keep code files that weren't deleted."""
    out = []
    for change in changes or []:
        if change.get("changeType") == "delete":
            continue
        path = change.get("item", {}).get("path", "")
        if path.endswith(CODE_EXTENSIONS):
            out.append(path)
    return out


def build_context(build_id: str, failed_step_names: list, logs: str,
                  sources: dict) -> dict:
    """Assemble the structured payload handed to the model."""
    return {
        "buildId": build_id,
        "failedSteps": failed_step_names,
        "logs": logs,
        "changedFiles": sources,
    }


def extract_fix_json(text: str) -> dict:
    """Tolerantly parse a model response into the fix dict.

    Handles raw JSON and JSON wrapped in ```/```json fences. Returns a
    no-fix result rather than raising on unparseable output.
    """
    if not text:
        return {"summary": "no confident fix", "files": []}
    s = text.strip()
    if s.startswith("```"):
        s = s.split("\n", 1)[-1] if "\n" in s else s
        if s.endswith("```"):
            s = s[: -3]
        if s.startswith("json"):
            s = s[len("json"):]
    s = s.strip()
    try:
        data = json.loads(s)
    except (ValueError, TypeError):
        return {"summary": "unparseable model response", "files": []}
    data.setdefault("summary", "")
    data.setdefault("files", [])
    if not isinstance(data.get("files"), list):
        data["files"] = []
    return data


def build_push_payload(new_branch: str, base_commit: str, files: list,
                       summary: str) -> dict:
    """Build the ADO Git 'pushes' body that creates the branch + commit."""
    changes = [{
        "changeType": "edit",
        "item": {"path": f["path"]},
        "newContent": {"content": f["content"], "contentType": "rawtext"},
    } for f in files]
    return {
        "refUpdates": [{"name": f"refs/heads/{new_branch}", "oldObjectId": base_commit}],
        "commits": [{"comment": f"AI fix: {summary}", "changes": changes}],
    }


def build_pr_payload(new_branch: str, base_branch: str, summary: str,
                     commit: str) -> dict:
    """Build the ADO Git 'pullrequests' body."""
    return {
        "sourceRefName": f"refs/heads/{new_branch}",
        "targetRefName": f"refs/heads/{base_branch}",
        "title": f"[AI self-heal] {summary}",
        "description": (
            f"Automated fix proposed for a pipeline failure on commit `{commit[:8]}`.\n\n"
            f"**Summary:** {summary}\n\n"
            "> Generated by the self-healing pipeline. Review before merging."
        ),
    }


def branch_name_for(commit: str) -> str:
    return f"{AI_BRANCH_PREFIX}{commit[:8]}"


# ------------------------------------------------------------------------- orchestration
def orchestrate(payload: dict, ado, request_fix, notify) -> dict:
    """Run the full heal flow with injected I/O.

    `ado` must expose:
        get_failed_steps(build_id) -> list[record]
        get_log_tail(build_id, log_id) -> str
        get_changed_files(commit) -> list[change]
        get_file_content(path, branch) -> str
        open_fix_pr(base_branch, base_commit, new_branch, files, summary) -> str|None (PR url)
    `request_fix(context) -> dict`   `notify(text) -> None`

    Returns a result dict: {"skipped"|"pr"|"summary": ...}.
    """
    branch = payload.get("branch", "main")

    if is_ai_branch(branch):
        logging.info("Failure is on an AI branch; skipping to avoid a heal loop.")
        return {"skipped": "ai-branch"}

    build_id = str(payload["buildId"])
    commit = payload["commit"]

    failed = ado.get_failed_steps(build_id)
    logs = "\n\n".join(
        f"### {s.get('name')}\n{ado.get_log_tail(build_id, s['log']['id'])}"
        for s in failed if s.get("log")
    )
    changed = filter_code_files(ado.get_changed_files(commit))
    sources = {p: ado.get_file_content(p, branch) for p in changed}

    context = build_context(build_id, [s.get("name") for s in failed], logs, sources)
    fix = request_fix(context)

    if fix.get("files"):
        new_branch = branch_name_for(commit)
        pr_url = ado.open_fix_pr(branch, commit, new_branch, fix["files"], fix["summary"])
        notify(f"🔧 Self-healing PR opened for build {build_id}: {fix['summary']}\n{pr_url}")
        return {"pr": pr_url, "summary": fix["summary"]}

    notify(f"⚠️ Build {build_id} failed; AI had no confident fix. Manual review needed.")
    return {"pr": None, "summary": fix.get("summary")}
